"""<modified on to updated at>

Revision ID: 179d3cd5a3bb
Revises: f5d8c2806d2d
Create Date: 2023-11-01 20:20:02.354163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179d3cd5a3bb'
down_revision = 'f5d8c2806d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('modified_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_on', sa.DATETIME(), nullable=False))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
