"""make favorite table

Revision ID: 1c8f60deebe7
Revises: 9f07f64e782d
Create Date: 2023-11-25 20:53:49.235922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8f60deebe7'
down_revision = '9f07f64e782d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_favorites_equipment_id_equipments')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_favorites_owner_id_owners')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
