"""equipment state history with total, available, reserved, and rented quality

Revision ID: 210f6115990e
Revises: aa88d7ae0bc3
Create Date: 2023-12-17 05:59:48.564879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210f6115990e'
down_revision = 'aa88d7ae0bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_state_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('available_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reserved_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rented_quantity', sa.Integer(), nullable=True))
        batch_op.drop_column('previous_quantity')
        batch_op.drop_column('new_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_state_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_quantity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('previous_quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('rented_quantity')
        batch_op.drop_column('reserved_quantity')
        batch_op.drop_column('available_quantity')
        batch_op.drop_column('total_quantity')

    # ### end Alembic commands ###
