"""add cart name

Revision ID: 227a96e94d19
Revises: d736bdfe12e9
Create Date: 2023-11-07 20:52:24.223828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227a96e94d19'
down_revision = 'd736bdfe12e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('cart_name')

    # ### end Alembic commands ###
