"""change total idle in summary to total available, same thing

Revision ID: 245041ae2770
Revises: 7599d95f3b88
Create Date: 2023-12-20 16:33:30.541444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245041ae2770'
down_revision = '7599d95f3b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_state_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_available', sa.Integer(), nullable=True))
        batch_op.drop_column('total_idle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_state_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_idle', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_available')

    # ### end Alembic commands ###
