"""add order number to order history

Revision ID: 37707e76984e
Revises: b198f1e8329c
Create Date: 2024-01-12 19:35:29.006600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37707e76984e'
down_revision = 'b198f1e8329c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
