"""<mispelled recipient>

Revision ID: 43860f1c5a37
Revises: 7001ad8c19c6
Create Date: 2023-10-10 21:31:22.362019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43860f1c5a37'
down_revision = '7001ad8c19c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.drop_column('recepient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recepient_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
