"""add individual item total to order history

Revision ID: 43c8959ddf72
Revises: c76c8c7cc121
Create Date: 2024-01-15 16:50:02.442074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c8959ddf72'
down_revision = 'c76c8c7cc121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('individual_item_total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.drop_column('individual_item_total')

    # ### end Alembic commands ###
