"""add equipment image column TEMP

Revision ID: 44d216b56655
Revises: 227a96e94d19
Create Date: 2023-11-13 14:00:52.836582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d216b56655'
down_revision = '227a96e94d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_column('equipment_image')

    # ### end Alembic commands ###
