"""<add user_type to messages>

Revision ID: 45081e801b11
Revises: 43860f1c5a37
Create Date: 2023-10-20 22:28:40.296594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45081e801b11'
down_revision = '43860f1c5a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
