"""add available quantity to equipment status

Revision ID: 471140720df2
Revises: c68fdab6c23c
Create Date: 2023-12-17 19:45:26.211921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471140720df2'
down_revision = 'c68fdab6c23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_status', schema=None) as batch_op:
        batch_op.drop_column('total_quantity')

    # ### end Alembic commands ###
