"""<add website row to equipment owners>

Revision ID: 481f9fcf9f97
Revises: 87f7bcf865ee
Create Date: 2023-08-28 18:08:49.780471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481f9fcf9f97'
down_revision = '87f7bcf865ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bannerImg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bannerImg', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
