"""change reviews to be tied to agreements, will be able to post if agreement completed

Revision ID: 68c5abc6c517
Revises: 68a5d927e784
Create Date: 2023-12-07 20:20:43.761174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c5abc6c517'
down_revision = '68a5d927e784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agreement_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reviews_cart_item_id_cart_items', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_agreement_id_agreements'), 'agreements', ['agreement_id'], ['id'])
        batch_op.drop_column('cart_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_item_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reviews_agreement_id_agreements'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_cart_item_id_cart_items', 'cart_items', ['cart_item_id'], ['id'])
        batch_op.drop_column('agreement_id')

    # ### end Alembic commands ###
