"""<break up location into postal, city, state, address + 2>

Revision ID: 6b413153b26b
Revises: f6d1a12c53e6
Create Date: 2024-01-03 20:39:15.377130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b413153b26b'
down_revision = 'f6d1a12c53e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(), nullable=True))
        batch_op.drop_column('location')

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(), nullable=True))
        batch_op.drop_column('location')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('country')

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('country')

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
