"""<subject context id added to message>

Revision ID: 7001ad8c19c6
Revises: 2af8edeced6c
Create Date: 2023-10-09 21:50:20.393519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7001ad8c19c6'
down_revision = '2af8edeced6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('subject')
        batch_op.drop_column('context_id')

    # ### end Alembic commands ###
