"""add state history and summary

Revision ID: 7c4641194d0e
Revises: 68c5abc6c517
Create Date: 2023-12-14 23:27:36.892610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4641194d0e'
down_revision = '68c5abc6c517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_state_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('previous_quantity', sa.Integer(), nullable=True),
    sa.Column('new_quantity', sa.Integer(), nullable=True),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_equipment_state_history_equipment_id_equipments')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_state_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_history_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('total_idle', sa.Integer(), nullable=True),
    sa.Column('total_rented_out', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_history_id'], ['equipment_state_history.id'], name=op.f('fk_equipment_state_summaries_equipment_history_id_equipment_state_history')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_state_summaries')
    op.drop_table('equipment_state_history')
    # ### end Alembic commands ###
