"""<reset to working>

Revision ID: 8edbf577e6cf
Revises: b13b71bf48f7
Create Date: 2023-10-23 17:18:36.844783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edbf577e6cf'
down_revision = 'b13b71bf48f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inboxes_context_id_messages', type_='foreignkey')
        batch_op.drop_column('context_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_inbox_id_inboxes', type_='foreignkey')
        batch_op.drop_column('inbox_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbox_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_messages_inbox_id_inboxes', 'inboxes', ['inbox_id'], ['id'])

    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_inboxes_context_id_messages', 'messages', ['context_id'], ['context_id'])

    # ### end Alembic commands ###
