"""split favorite table to user and owner favorite

Revision ID: 926842e796b1
Revises: 1c8f60deebe7
Create Date: 2023-11-25 21:47:38.673011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926842e796b1'
down_revision = '1c8f60deebe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_owner_favorites_owner_id_owners')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_owner_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_user_favorites_equipment_id_equipments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('relationship_type', sa.VARCHAR(), nullable=True),
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name='fk_favorites_equipment_id_equipments'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name='fk_favorites_owner_id_owners'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorites_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_favorites')
    op.drop_table('owner_favorites')
    # ### end Alembic commands ###
