"""<include context in inbox>

Revision ID: 92b1cb1517cb
Revises: 5e55f6e60142
Create Date: 2023-10-23 16:54:20.043466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b1cb1517cb'
down_revision = '5e55f6e60142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_inboxes_context_id_messages'), 'messages', ['context_id'], ['context_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inboxes_context_id_messages'), type_='foreignkey')
        batch_op.drop_column('context_id')

    # ### end Alembic commands ###
