"""<add website row to equipment owners>

Revision ID: 93ed9d58267b
Revises: 481f9fcf9f97
Create Date: 2023-08-28 18:09:14.441662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ed9d58267b'
down_revision = '481f9fcf9f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###
