"""<re-create, cart, cart item, equipment price>

Revision ID: 98749c802194
Revises: 179d3cd5a3bb
Create Date: 2023-11-02 15:45:55.234718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98749c802194'
down_revision = '179d3cd5a3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=True),
    sa.Column('daily_rate', sa.Integer(), nullable=True),
    sa.Column('weekly_rate', sa.Integer(), nullable=True),
    sa.Column('promo_rate', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_equipment_prices_equipment_id_equipments')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_prices')
    # ### end Alembic commands ###
