"""remove age and onboard link from owners

Revision ID: 98b6793504a8
Revises: b5dafc1fe086
Create Date: 2024-01-05 18:33:12.428794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b6793504a8'
down_revision = 'b5dafc1fe086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_column('stripe_onboard_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_onboard_link', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
