"""add total cancelled to state summary saved

Revision ID: aa88d7ae0bc3
Revises: 7910163c9c6f
Create Date: 2023-12-16 15:57:22.000827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa88d7ae0bc3'
down_revision = '7910163c9c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_state_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cancelled', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_state_summaries', schema=None) as batch_op:
        batch_op.drop_column('total_cancelled')

    # ### end Alembic commands ###
