"""add owner_id to user_favorites table

Revision ID: ae5134e99ec5
Revises: 926842e796b1
Create Date: 2023-11-26 21:10:16.687919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5134e99ec5'
down_revision = '926842e796b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_favorites_owner_id_owners'), 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_favorites_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
