"""<try relationship with messages and inboxes 3>

Revision ID: b13b71bf48f7
Revises: 92b1cb1517cb
Create Date: 2023-10-23 17:14:58.144235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13b71bf48f7'
down_revision = '92b1cb1517cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbox_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_inbox_id_inboxes'), 'inboxes', ['inbox_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_inbox_id_inboxes'), type_='foreignkey')
        batch_op.drop_column('inbox_id')

    # ### end Alembic commands ###
