"""add stripe onboard link to owners

Revision ID: b5dafc1fe086
Revises: e6208129bfa8
Create Date: 2024-01-05 13:50:25.641929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5dafc1fe086'
down_revision = 'e6208129bfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_onboard_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_column('stripe_onboard_link')

    # ### end Alembic commands ###
