"""rental rate to cart

Revision ID: bf8538b6d73a
Revises: 9bebe2b5a60b
Create Date: 2023-11-16 19:27:38.137761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8538b6d73a'
down_revision = '9bebe2b5a60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_rate', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('rental_rate')

    # ### end Alembic commands ###
