"""add created at to order history, origin to agreement comment

Revision ID: ce654e84582c
Revises: 37707e76984e
Create Date: 2024-01-15 14:38:43.474010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce654e84582c'
down_revision = '37707e76984e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreement_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(), nullable=True))

    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('agreement_comments', schema=None) as batch_op:
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
