"""equipment status current quality changed to available

Revision ID: d69f9001cf31
Revises: 210f6115990e
Create Date: 2023-12-17 06:07:33.969959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69f9001cf31'
down_revision = '210f6115990e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rented_quantity', sa.Integer(), nullable=True))
        batch_op.drop_column('current_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('rented_quantity')
        batch_op.drop_column('available_quantity')

    # ### end Alembic commands ###
