"""<add bio (nullable) to user and owners>

Revision ID: e86cd846be13
Revises: b9f1e1eb819d
Create Date: 2023-11-20 14:12:39.457126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86cd846be13'
down_revision = 'b9f1e1eb819d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
