"""checking if boolean update was needed

Revision ID: edf149790072
Revises: 55025b824703
Create Date: 2023-11-30 18:07:03.955917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf149790072'
down_revision = '55025b824703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.alter_column('delivery',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.alter_column('delivery',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
