"""include equipment foreign key id in equipment state summary

Revision ID: f6d1a12c53e6
Revises: 245041ae2770
Create Date: 2023-12-21 19:15:07.761043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d1a12c53e6'
down_revision = '245041ae2770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_state_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_equipment_state_summaries_equipment_id_equipments'), 'equipments', ['equipment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_state_summaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_equipment_state_summaries_equipment_id_equipments'), type_='foreignkey')
        batch_op.drop_column('equipment_id')

    # ### end Alembic commands ###
